- cmd/root/root.go
- cmd/test/test.go
- cmd/test/unit/unit.go
- cmd/test/unit/unit_test.go
- go.mod
- internal/pkg/pdkshell/path.go
- internal/pkg/pdkshell/path_test.go
- internal/pkg/pdkshell/path_windows.go
- internal/pkg/pdkshell/path_windows_test.go
- internal/pkg/pdkshell/pdkshell.go
- internal/pkg/pdkshell/pdkshell_test.go
- internal/pkg/pdkshell/pdkshell_windows_test.go
- internal/pkg/utils/utils.go
- internal/pkg/utils/utils_test.go
- main.go
> (GH-7) pdk shell

- CHANGELOG.md
- cmd/new/new.go
- internal/pkg/pct/pct.go
- internal/pkg/pct/pct_test.go
Add a new func to the `pct` pacakge to retrieve a PCT from the local filesystem. Modify `pct new` to return a formatted error if the PCT is not found.
> (GH-29) Error if template not found

- .github/workflows/release.yml
- .goreleaser.yml
- CONTRIBUTING.md
- build.ps1
- build.sh
Update build scripts to call the goreleaser build to ensure a consistent binary is produced locally.
Update the goreleaser script to produce a production ready binary and set the Github release info.
> (maint) Align build scripts

- .gitignore
- cmd/new/new.go
- internal/pkg/pct/pct.go
- internal/pkg/pct/pct_test.go
This commit fixes an issue whereby `item` templates would be added to the parent directory rather than the current working directory (CWD).
By default `pct new` will add content from templates in the CWD.  The behaviour can be overridden by supplying the `--output` flag
> (GH-27) fix creation path of 'item' templates

- docs/pct/README.md
This provides an initial set of instructions on how to use the pct tool to create content using Puppet Content Templates
> (GH-23) Initial docs for PCT

- .github/workflows/acceptance.yml
- .github/workflows/release.yml
- .goreleaser.yml
- build.ps1
- build.sh
- cmd/new/new.go
- internal/pkg/pct/pct.go
This commit modifies `new.go` to set the default template path to
be the `$INSTALL_ROOT/templates` directory, enabling a "ready to go"
experience for the PCT LA. When a user runs `pct new --list` they
will see the default templates we have elected to ship with the package.
Also added a warning log message in the `pct#Get` function to alert
the user if no templates could be found.
The build scripts can now create a build for local development
purposes or a production ready snapshot using the arguments, "build"
or "snapshot", respectively. The scripts will also handle fetching
the default content templates from `puppetlabs/baker-round`.
> (GH-20) Bundle pct-templates with pkg

- cmd/new/new.go
ensures that if a user uses autocomplete before executing a function that the localTemplateCache is set.
> (maint) Fix new completion

- acceptance/new_test.go
- cmd/new/new.go
- go.mod
- internal/pkg/pct/pct.go
- internal/pkg/pct/pct_test.go
The `info` flag prints out the default configuration of a template, as found in `pct-config.yml` for the desired template id.
> (GH-43) Add info flag to pct new

- internal/pkg/pdkshell/pdkshell.go
- internal/pkg/utils/utils.go
Update to replace `pdk` removal with `pct` removal
> (GH-64) Strip pct from command name

- .gitignore
- internal/pkg/pct/pct.go
- internal/pkg/pct/pct_test.go
This change ensures that empty files within a content directory are deployed. Previously empty file content assumed an error had occurred.
> (GH-65) Allow deployment of empty files 

- tools/install.ps1
- tools/install.sh
Adds an `install.[ps1|sh]` script to:
- Fetch the latest tag from the puppetlabs/pdkgo repo
- Download the latest PCT archive to `$HOME/.puppetlabs/pct`
Closes #67
> (GH-67) Add installation scripts for PCT

- cmd/root/root.go
- main.go
Prior to this change, the trace log line from root#InitConfig
would always output, regardless of log level as zerolog was being
initialized after this point.
This change breaks out the zerolog initialisation in to it's own
method then initializes it from the cobra.OnInitialize method,
prior to any subsequent logging method calls.
Closes: #107
> (GH-107) Initialize zerolog via cobra.OnInitialize method

- tools/install.sh
Installing pdkgo with the curl script today failed trying to extract
from the wrong URL, because the variable `$ver` had ended up with two
matches (`0.1.0 0.1.0-pre`).  
This patch:
* Ensures there will only be a single version in `$ver`
* Fails the script if it encounters errors
* Adds quotes around variables used as arguments, so spaces won't appear
to be multiple arguments
PS: I left out `set -o pipefail` because POSIX sh doesn't support it,
but it be a would good idea, on account of all the piped commands.
Closes #125
> (GH-125) Fix `$ver` bug in download script

- .github/workflows/codequality.yml
rule out that the go mod tidy issue observed [here](https://github.com/puppetlabs/pdkgo/runs/2792130365?check_suite_focus=true#step:3:5) is due to running a different version of go for the codequality checks
> (maint) ensure code quality check run the correct version of go 

- internal/pkg/pdkshell/env_var.go
- internal/pkg/pdkshell/env_var_test.go
- internal/pkg/pdkshell/os_utils.go
- internal/pkg/pdkshell/pdkshell.go
Prior to this commit, if a user was managing their rubies with RVM,
execution of the PDK from the PCT's pdkshell package would fail due
to the RVM injections in PATH taking priority over the PDK's bundled
2.4 instance.
This commit emulates the unsetting of the necessary ENV VARS, similar
to the [pdk_env_wrapper](https://github.com/puppetlabs/pdk-vanagon/blob/main/resources/files/posix/pdk_env_wrapper) script, whilst preserving any user / system defined ENV VARs.
Closes: #15
> (GH-15) Unset necessary env vars in pdkshell

- CHANGELOG.md
Add changlog entries for 0.2.0 release. This also formats the Github issue links properly and fixes the links to each version header.
> (maint) Update CHANGELOG for 0.2.0

- cmd/version/version.go
Remove the `v` prefix from the github release url generated when running `pct -v`. This project generates tags with just numbers and does not use the `v` prefix.
> (GH-139) Fix version command release output

- internal/pkg/gzip/gzip_utils.go
- internal/pkg/pct/build.go
- internal/pkg/pct/build_test.go
- internal/pkg/pct/gzip_utils_mock.go
- internal/pkg/pct/io_utils_mock.go
- internal/pkg/pct/os_utils_mock.go
- internal/pkg/pct/tar_utils_mock.go
- internal/pkg/pct/utils_mock.go
- internal/pkg/tar/tar_utils.go
- internal/pkg/utils/io_utils.go
- internal/pkg/utils/os_utils.go
- internal/pkg/utils/utils.go
This commit adds the `build` method, which will take a given
template path and output dir, and generate a .tar.gz of the
template path's contents.
This work is built upon the previous effort in GH-137 which
implemented the TAR and GZIP utility methods.
Some preflight sanity checks are performed on the template path
to ensure it meets the minimum requirements of a PCT:
- Are we in a valid module's root dir?
- Does the directory path exist?
- Does it contain a `pct-config.yml` at root?
- Does it contain a `content` dir at root?
If those conditions are satisfied, the template directory is
first TAR'd and then GZIP'd, and the resulting `.tar.gz` output to
the specified directory.
If any operation fails along the way (pre checks / TAR/GZ operation),
an error is returned.
Closes: #145
> (GH-145) Add ability to tar.gz a given template

- internal/pkg/pct/build_test.go
- internal/pkg/pct/pct_test.go
- internal/pkg/tar/tar_test.go
Prior to this commit, when running linting checks locally, you
would encounter the following error:
```
SA9002: file mode '750' evaluates to 01356; did you mean '0750'
```
This commit fixes the perm value to avoid this error.
Also changes a `0755` perm setting to a more secure `0750` in
`tar_test.go`
> (MAINT) Change `Mkdir(All)?` perms from 750 -> 0750

- CHANGELOG.md
- acceptance/build/testdata/good-project/pct-config.yml
- acceptance/build/testdata/no-content-dir-project/pct-config.yml
- build.ps1
- build.sh
- cmd/build/build.go
- cmd/root/root.go
- internal/pkg/pct/build.go
- internal/pkg/pct/build_test.go
- internal/pkg/pct/pct.go
Ensures that the attributes of id, author and version are present within pct-config.yml. These are required for installing templates within a namespaces and version directory structure.
> (GH-185) Validate a pct-config.yml before building 

- acceptance/new/new_test.go
- cmd/new/new.go
- go.mod
- internal/pkg/pct/pct.go
- internal/pkg/pct/pct_test.go
Prior to this commit, there were multiple calls to `pctApi.List()`
when the `cmd/new` package was being initialised.
This commit reduces this to a single call, performed in the
`PreRunE` stage of the `cobra.Command` instantiation, and caches
the result to a new variable called `cachedTemplates`.
Any subsequent calls to `pctApi.List()` now instead use the
cached data.
Also, prior to this commit, the `pctApi.GetInfo` and `pctApi.Get`
function arguments were:
```go
(templateCache string, selectedTemplate string)
```
This commit changes the method signatures of these methods to:
```go
(templateDirPath string)
```
`pctApi.GetInfo` will now need to receive the full path to the
template that you wish to retrieve info on. The returned data is
still the same.
Any calls made to these methods has …
> (GH-201) Cache PCT templates in `pct new` preExecute method

- CHANGELOG.md
- README.md
- acceptance/install/install_test.go
- internal/pkg/httpclient/httpclient.go
- internal/pkg/mock/httpclient.go
- internal/pkg/pct/install.go
- internal/pkg/pct/install_test.go
- main.go
Prior to this commit the only way to install a PCT template was to have
already downloaded the tar.gz locally.
This commit updates the `Install` function to handle a `templatePkg`
specified as a valid URL, downloading the file to a temporary folder
and then handing the file off to the remainder of the function to
process like any local file.
This commit also implements the new `downloadTemplate` function, which
handles downloading and placing the template archive file, returning the
path to it.
TODO: unit/acceptance tests
> (GH-184) Enable install of remote templates

- cmd/pmr/get/get.go
- cmd/pmr/get/puppet.go
- cmd/pmr/main.go
- cmd/pmr/root/root.go
- cmd/pmr/set/puppet.go
- cmd/pmr/set/set.go
- internal/pkg/config/config.go
- internal/pkg/puppet/container.go
This commit pulls the work @da-ar did in his docker POC:
- https://github.com/da-ar/pdkgo/commits/version-poc
To the PRM binary, reworking it slightly where needed. This commit does not add or change any functionality, merely moves it into the correct binary.
What this PR currently enables:
- Setting/Getting the version of the Puppet Runtime available as a docker container to PRM.
Future PRs will be needed to generalize and productize these basic interfaces.
Resolves #209
> (GH-208) Port prototype of docker get/set for Puppet

- go.mod
- go.sum
- pkg/telemetry/telemetry.go
Prior to this commit, a binary reporting telemetry would report on the Operating System and Architecture of the machine PCT was running on; this commit adds a new data key for UUID to enable per-machine telemetry and analysis.
The UUID itself is further hashed to our own namespace to prevent even the possibility of leaking a UUID which could be reversed to discover the user.
Resolves #223
> (GH-223) Implement UUID for telemetry

- .gitignore
- README.md
- docs.sh
Overview of PR:
- Added the `docs.sh` script that installs the devx documentation site to the `docs/site` 
directory of the project.
- Added instructions pertaining to the local installation and running of the
documentation site.
Resolves: #295
> (GH-295) Add documentation site install script

- docs.ps1
Overview of PR:
- Added the `docs.ps1` script to install the devx documentation site to the `docs\site`
directory. It effectively works the same way as its unix shell script
counterpart.
> (GH-303) Add Powershell docs install script

- acceptance/build/build_test.go
- acceptance/install/install_test.go
- acceptance/new/new_test.go
- acceptance/testutils/testutils.go
Prior to this commit, the utility functions within the `testutils`
package were working on the assumption that `pct` was the only
binary we would need to invoke for acceptance tests.
This commit genericises the utility methods by:
- Adding a `SetAppName` function
- Replacing any hardcoded string literals of "pct" and referencing
the `app` var set by `SetAppName`
- Renamed the `RunPctCommand` func to `RunAppCommand`
This change will allow us to import this package in to other
repos and use it for acceptance tests there. The first use case
will be for `puppetlabs/prm`.
Also part of this commit is the update of the tests that live in
the `acceptance` dir based on the above changes
Resolves: #309
> (GH-309) Genericise `acceptance/testutils` package

- CHANGELOG.md
- cmd/new/new.go
Prior to this PR, the `--format` flag when calling `pct new` did not autocomplete the options or suggest them.
This PR corrects that bug and ensures that:
1. Attempting to autocomplete without specifying any text after `--format` cycles through the available options
2. Attempting to autocomplete with a partial match for any valid option cycles through all valid options which match
> (MAINT) Fix format autocomplete for new command

- .github/workflows/acceptance.yml
We encountered a dependency issue using `go get` to fetch
`goreleaser` on the PRM workflows. The method we should have been
using anyway was `go install github.com/goreleaser/goreleaser@latest`
This commit updates the `acceptance.yml` workflow to use this
method
> (MAINT) Switch to go install goreleaser on GHA workflows

- acceptance/install/install_test.go
- pkg/install/install.go
- pkg/install/install_test.go
Overview of PR:
- To genericize `pct install` errors, so that error output is more understandable in the `prm` program.
> Genericize PCT install errors

- go.mod
- go.sum
In this PR:
- This PR drops the replacement directive from `go.mod` so that we
reference the package correctly on Github.
> (MAINT) Remove local directive for docs module

- pkg/telemetry/telemetry.go
Added an additional attribute to the gathered Honeycomb telemetry, reporting whether or not the code has been run as part of our CI or not.
Link to function used to retrieve CI status:
https://zetcode.com/golang/env/#:~:text=or%20viper%20libraries.-,Go%20os.Getenv,-The%20Getenv%20retrieves
> (GH-331) Update Telemetry to report whether run is on CI

- internal/pkg/pct_config_processor/pct_config_processor.go
- internal/pkg/pct_config_processor/pct_config_processor_test.go
- main.go
- pkg/config_processor/config_processor.go
- pkg/install/install.go
- pkg/install/install_test.go
- pkg/mock/install_config.go
Prior to this PR, the private processor included the `ProcessConfig()` public function which called the private functions `readConfig()` and `setupTemplateNamespace()` to place a package in the right folder structure so that it is recognized as an installed package.
This is an install function placed in the config processor.
This PR replaces the `ProcessConfig()` function in the `config_processor.ConfigProcessorI` interface with `GetConfigMetadata()`, which returns the new `ConfigMetadata` struct also newly defined in `config_processor`. This enables a consumer of a `ConfigProcessorI` implementation to retrieve the metadata needed to install a package generically. The prior implementation conflated configuration processing with install logic.
This PR adds a new public function to the …
> (GH-349) Genericize `install` package logic and move it from the private config processor into the package

- acceptance/testutils/testutils.go
- build.ps1
- build.sh
As of go 1.18, the GOAMD64 has been introduced to represent the different microarchitecture levels to compile for when GOARCH is amd64.
It would appear that GOAMD64 is not available in the runtime package, so in this PR we are making an assumption that we will be building for the default of v1. This is currently true for goreleaser config in PRM and PCT.
> (MAINT) Handle default for GOAMD64 builds

- cmd/build/build.go
- cmd/build/build_test.go
Bug summary:
`./` prepended to the beginning of a `--sourcedir` path causes issues
when building the package. The resulting package could not be installed.
The fix:
Clean the `sourceDir` string.
> (GH-348) Fix build path mishandle
